name: Tests

on:
   push:
      branches:
         - dev
   pull_request:
      branches:
         - dev

permissions:
   contents: write

jobs:
   push_to_main:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Set up git
           run: |
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"

         - name: Push changes to main
           run: |
              git checkout -b main
              git fetch
              git config pull.rebase true
              git pull origin main dev
              git branch --set-upstream-to=origin/dev main
              git push -u origin main
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
