name: Execute Tests

on:
   push:
      branches:
         - dev
   pull_request:
      branches:
         - dev

permissions:
   contents: write

jobs:
   test:
      runs-on: ubuntu-latest

      strategy:
         matrix:
            php-version: [8.2, 8.3, 8.4]
            include:
               - php-version: 8.3

      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Set up PHP
           uses: shivammathur/setup-php@v2
           with:
              php-version: ${{ matrix.php-version }}
              extensions: mbstring, intl, curl, dom, fileinfo
              tools: composer

         - name: Cache Composer packages
           id: composer-cache
           uses: actions/cache@v3
           with:
              path: vendor
              key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
              restore-keys: |
                 ${{ runner.os }}-php-

         - name: Install dependencies
           run: composer install --prefer-dist --no-progress

         - name: Run Tests
           run: composer run-script test

   push_to_main:
      runs-on: ubuntu-latest
      needs: test
      if: success()

      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Push changes to main
           run: |
              git fetch origin main dev
              git checkout main
              git config pull.rebase false
              git pull origin main
              git merge origin/dev --allow-unrelated-histories --no-ff
              git push origin main
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
